/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FormRouteImport } from './routes/form'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BodyRouteImport } from './routes/body'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminMealTestRouteImport } from './routes/admin.meal-test'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMealTestRoute = AdminMealTestRouteImport.update({
  id: '/admin/meal-test',
  path: '/admin/meal-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof BodyRoute
  '/chat': typeof ChatRoute
  '/form': typeof FormRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/welcome': typeof WelcomeRoute
  '/workouts': typeof WorkoutsRoute
  '/admin/meal-test': typeof AdminMealTestRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof BodyRoute
  '/chat': typeof ChatRoute
  '/form': typeof FormRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/welcome': typeof WelcomeRoute
  '/workouts': typeof WorkoutsRoute
  '/admin/meal-test': typeof AdminMealTestRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof BodyRoute
  '/chat': typeof ChatRoute
  '/form': typeof FormRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/welcome': typeof WelcomeRoute
  '/workouts': typeof WorkoutsRoute
  '/admin/meal-test': typeof AdminMealTestRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/body'
    | '/chat'
    | '/form'
    | '/insights'
    | '/library'
    | '/nutrition'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/welcome'
    | '/workouts'
    | '/admin/meal-test'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/body'
    | '/chat'
    | '/form'
    | '/insights'
    | '/library'
    | '/nutrition'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/welcome'
    | '/workouts'
    | '/admin/meal-test'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/body'
    | '/chat'
    | '/form'
    | '/insights'
    | '/library'
    | '/nutrition'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/welcome'
    | '/workouts'
    | '/admin/meal-test'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BodyRoute: typeof BodyRoute
  ChatRoute: typeof ChatRoute
  FormRoute: typeof FormRoute
  InsightsRoute: typeof InsightsRoute
  LibraryRoute: typeof LibraryRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkoutsRoute: typeof WorkoutsRoute
  AdminMealTestRoute: typeof AdminMealTestRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/meal-test': {
      id: '/admin/meal-test'
      path: '/admin/meal-test'
      fullPath: '/admin/meal-test'
      preLoaderRoute: typeof AdminMealTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BodyRoute: BodyRoute,
  ChatRoute: ChatRoute,
  FormRoute: FormRoute,
  InsightsRoute: InsightsRoute,
  LibraryRoute: LibraryRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  WelcomeRoute: WelcomeRoute,
  WorkoutsRoute: WorkoutsRoute,
  AdminMealTestRoute: AdminMealTestRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
